Listing 3.28 Removing the type annotations in the index.ts file in the primer folder
index.ts(6,5): error TS2367: This comparison appears to be unintentional because the types 'number' and 'string' have no overlap.